package tatai.model;

import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;

public class CustomLevel extends Level {
	
	/**
	 * This class extends the Level class for the CustomLists. It retrieves the equations that are generated by the user and 
	 * selects an equation at random to display.
	 */

	private ArrayList<Integer> _answers;
	private ArrayList<String> _equations;
	private int _numEquations;
	private String _question; 

	public CustomLevel(int index) {
		CustomLists _customLists = CustomLists.getInstance();//contains all custom lists and retrieves the singleton instance.
		
		if (index < 0 || index >= _customLists.getLists().size()) { //means index doesn't correspond to any list
			throw new IllegalArgumentException();
		} else {
			//get equations and answers of that list
			_equations = _customLists.getEquations(index);
			_answers = _customLists.getAnswer(index);
			
			//get number of equations in that list
			_numEquations = _customLists.getEquations(index).size();
		}
	}

	@Override
	public String getQuestion() {
		return _question;
	}

	//Selects a question from the custom list at random and also converts the answer from the question to Maori for recognition.
	@Override
	public void generateQuestion() {
		int question = ThreadLocalRandom.current().nextInt(0, _numEquations);
		_question = _equations.get(question);
		int answer = _answers.get(question);
		convertToMaori(answer);
	}

}
